name: Deploy to App Engine

on:
  push:
    branches: 
      - main

jobs:
  deploy_to_gcloud:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'gcloud auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/11549781461/locations/global/workloadIdentityPools/nutrobo-pool/providers/nutrobo-provider'
        service_account: 'nutrobo-app@appspot.gserviceaccount.com'

    - id: 'gcloud deploy'
      uses: 'google-github-actions/deploy-appengine@v2'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.version_url }}"'
            