name: Deploy to App Engine

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deploy
      id: deploy
      uses: google-github-actions/deploy-appengine@v2
      with:
        deliverables: app.yaml cron.yaml
        version: v1
        project_id: ${{ secrets.GCLOUD_PRJ_ID }}
        credentials: ${{ secrets.GCLOUD_CREDENTIALS }}

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
            