name: Deploy to App Engine

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_CREDENTIALS }}'

    - name: Deploy
      uses: google-github-actions/deploy-appengine@v2

    - name: Test
      run: curl "${{ steps.deploy.outputs.url }}"
            