name: Deploy to App Engine

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Git config
      run: 'git config --global user.email "a@aveth.com" && git config --global user.name "aveth"'

    - name: GCloud service account credentials
      run: 'mkdir .secrets && ${{ secrets.NUTROBO_SERVICE_ACCOUNT }} | base64 --decode > ".secrets/nutrobo-service-account.json"'

    - name: GCloud authentication
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCLOUD_CREDENTIAL }}'

    - name: Bump version
      run: 'npm version $(cat package.json | jq -r ".version")-${{ github.run_number }}'

    - name: Deploy to App Engine
      uses: google-github-actions/deploy-appengine@v2
      
            
